import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, HeadingLevel, WidthType, BorderStyle } from 'docx';
import { DEIDENTIFIED_HEADER } from './deidentify.js';

const s = (v) => v == null || v === '' ? '—' : String(v);
const pct = (v) => `${Math.round((Number(v) || 0) * 100)}%`;
const cell = (v, bold = false) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: s(v), bold })] })] });
const table = (headers, rows) => new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, borders: { top: { style: BorderStyle.SINGLE, size: 4 }, bottom: { style: BorderStyle.SINGLE, size: 4 }, left: { style: BorderStyle.SINGLE, size: 4 }, right: { style: BorderStyle.SINGLE, size: 4 }, insideHorizontal: { style: BorderStyle.SINGLE, size: 2 }, insideVertical: { style: BorderStyle.SINGLE, size: 2 } }, rows: [new TableRow({ children: headers.map(h => cell(h, true)) }), ...rows.map(r => new TableRow({ children: r.map(v => cell(v)) }))] });
const heading = (text, level = HeadingLevel.HEADING_1) => new Paragraph({ text: s(text), heading: level });
const para = (text, bold = false) => new Paragraph({ children: [new TextRun({ text: s(text), bold })] });
const bullets = (xs, numbered = false) => (xs || []).map((x, i) => new Paragraph({ text: `${numbered ? `${i + 1}. ` : '• '}${s(x?.text || x)}` }));
const header = (payload, title) => { const c = payload.client || {}, a = payload.assessment || {}; const banner = payload.deidentified ? [new Paragraph({ children: [new TextRun({ text: payload.deidentified_header || DEIDENTIFIED_HEADER, bold: true, color: 'CC0000' })] })] : []; return [...banner, heading(title), para(`Client: ${s(c.first_name)} ${s(c.last_name)} | DOB: ${s(c.date_of_birth)} | Gender: ${s(c.gender)}`), para(`Assessment: ${s(a.title)} | Assessment date: ${s(a.assessment_date)} | Assessor: ${s(a.assessor)}`), para(`Generated: ${new Date(payload.generated_at || Date.now()).toLocaleDateString()} — ${payload.is_preliminary ? 'PRELIMINARY' : 'FINAL'}`, true)]; };
const signatures = (payload) => [heading('Signatures'), para('In-app sign-off records are workflow records; formal legally-binding e-signature integration is pending.'), ...(payload.signatures || []).flatMap((x) => { const so = (payload.sign_offs || []).find(y => y.signatory_role === x.role_code && y.status === 'signed'); return [para(x.role, true), para(so ? `Signed by ${s(so.signatory_name)}${so.signed_at ? ` on ${String(so.signed_at).slice(0,10)}` : ''}` : 'Signature: ______________________________    Printed name: ______________________________    Date: ______________')]; })];
const baseDoc = (children) => new Document({ sections: [{ properties: {}, children }] });

export function docxForReport(p) { const out = [...header(p, 'Functional Behavior Assessment Report')]; const c=p.client||{}; out.push(heading('Client information',2), table(['Field','Value'], [['Name',`${s(c.first_name)} ${s(c.last_name)}`],['Date of birth',c.date_of_birth],['Gender',c.gender],['Consent',c.consent_status_label]])); out.push(heading('Target behaviors',2), table(['Behavior','Operational definition','Safety','Measurement'],(p.behaviors||[]).map(b=>[b.name,b.operational_definition,b.safety_classification_label,b.baseline_measurement_type_label]))); out.push(heading('Data summary',2), table(['Behavior','Observations','Statistics'],(p.data_summary?.per_behavior_stats||[]).map(x=>[x.target_behavior_name,x.stats?.count ?? (p.data_summary.per_behavior||[]).find(y=>y.target_behavior_id===x.target_behavior_id)?.count,s(x.stats?.mean != null ? `Mean ${x.stats.mean}` : '')]))); out.push(heading('ABC analysis',2)); (p.abc||[]).forEach(x=>{out.push(heading(x.target_behavior_name,3),para(`Top antecedents: ${(x.top_antecedents||[]).map(y=>`${y.label} (${y.count})`).join(', ')||'none recorded'}`),para(`Top consequences: ${(x.top_consequences||[]).map(y=>`${y.label} (${y.count})`).join(', ')||'none recorded'}`));}); out.push(heading('Function hypotheses',2),table(['Behavior','Function','Confidence','Rationale / interpretation'],(p.hypotheses||[]).map(h=>[h.target_behavior_name,h.function_label,pct(h.confidence),`${s(h.rationale)} ${s(h.interpretation)}`]))); out.push(heading('Data quality',2),para(`ABC completeness: ${pct(p.data_quality?.data_completeness)}`),...bullets(p.data_quality?.notes)); out.push(...signatures(p)); return baseDoc(out); }

export function docxForBip(p) { const out=[...header(p,'Behavior Intervention Plan')]; (p.behaviors||[]).forEach(b=>{out.push(heading(b.name,2),para(`Definition: ${s(b.operational_definition)}`),para(`Safety: ${s(b.safety_classification_label)}`),para(`Hypothesized function: ${b.hypothesized_function ? `${b.hypothesized_function.function_label} (${pct(b.hypothesized_function.confidence)})` : 'Not yet established'}`,true),heading('Antecedent strategies',3),...bullets(b.antecedent_strategies,true),heading('Replacement skills',3),para(b.replacement_skills?.description),para(`Mastery criteria: ______________________________    Review interval: ______________________________`),para(b.replacement_skills?.prompting_note),heading('Consequence strategies',3),...bullets(b.consequence_strategies,true),heading('Data collection plan',3),para(b.data_collection_plan?.data_sheet_reference));}); out.push(...signatures(p)); return baseDoc(out); }

export function docxForCrisis(p) { const out=[...header(p,'Crisis Procedure / Safety Plan'),heading('Trigger behaviors',2)]; if(p.has_triggers) (p.trigger_behaviors||[]).forEach(b=>out.push(heading(b.name,3),para(`Definition: ${s(b.operational_definition)} | Classification: ${s(b.safety_classification_label)}`),para(s(b.guidance)))); else out.push(para(p.empty_state_note)); out.push(heading('Response steps',2),...bullets(p.response_steps,true),heading('Roles',2),table(['Role','Name','Duty'],(p.roles||[]).map(x=>[x.role||' ',x.name||' ',x.duty||' '])),heading('Debrief',2),...bullets(p.debrief?.steps),para('Debrief date: __________________  Participants: __________________  Review notes: __________________'),heading('Emergency contacts',2),table(['Contact','Details'],[['Primary',p.emergency_contacts?.contact_1],['Secondary',p.emergency_contacts?.contact_2],['Local emergency number',p.emergency_contacts?.local_emergency_number]]),...signatures(p)); return baseDoc(out); }

export function docxForDataSheet(p) { const out=[...header(p,'Blank Observation Data Sheet'),para(p.observation_instructions)]; if(!(p.sheets||[]).length) out.push(para('No target behaviors have been defined; no data sheets are available.')); (p.sheets||[]).forEach(sh=>{out.push(heading(sh.behavior_name,2),para(`Operational definition: ${s(sh.operational_definition)} | Measurement: ${s(sh.measurement_type_label)}`)); const rows=Array.from({length:20},()=>['','','','','']); out.push(table(['Date / Time','Setting','Antecedent','Consequence',sh.value_column_label],rows));}); return baseDoc(out); }

export function docxForProgressReport(p) {
 const out = [...header(p, `Progress Report — ${s(p.period_label)}`), heading('Executive summary',2), para(p.executive_summary), heading('Key behavior metrics',2)];
 const metrics = (p.metrics?.per_behavior || []).map((m,i) => { const t=(p.trends?.per_behavior || [])[i] || {}; const arrow=t.direction==='worsened'?'▲ worsened':t.direction==='improved'?'▼ improved':t.direction==='stable'?'→ stable':'— baseline'; return [m.behavior_name,m.point_count,m.frequency_mean_per_observation_day == null ? '—' : Number(m.frequency_mean_per_observation_day).toFixed(2),arrow]; });
 out.push(table(['Behavior','Points','Frequency mean/day','Trend'], metrics), heading('Plan-adjustment recommendations',2));
 const recs=(p.recommendations||[]).map(r => `${String(r.priority).toUpperCase()} — ${r.text} (${r.timeframe})`); out.push(...(recs.length ? bullets(recs,true) : [para('No recommendations recorded.')]));
 out.push(heading('Implementation plan',2), table(['Action','Owner','Due'], [[' ',' ',' '],[' ',' ',' '],[' ',' ',' ']]), para(p.not_yet_available), ...signatures(p)); return baseDoc(out);
}

export async function pack(doc) { return Packer.toBuffer(doc); }
