import PDFDocument from 'pdfkit';
import { DEIDENTIFIED_HEADER } from './deidentify.js';
const s = (v) => v == null || v === '' ? '—' : String(v);
const pct = (v) => `${Math.round((Number(v) || 0) * 100)}%`;
function lines(p, title) {
 const c=p.client||{}, a=p.assessment||{};
 return [p.deidentified ? (p.deidentified_header || DEIDENTIFIED_HEADER) : null, title,
  `Client: ${s(c.first_name)} ${s(c.last_name)} | DOB: ${s(c.date_of_birth)} | Gender: ${s(c.gender)}`,
  `Assessment: ${s(a.title)} | Assessment date: ${s(a.assessment_date)} | Assessor: ${s(a.assessor)}`,
  `Generated: ${new Date(p.generated_at || Date.now()).toLocaleDateString()} — ${p.is_preliminary ? 'PRELIMINARY' : 'FINAL'}`].filter(Boolean);
}
function addTable(doc, headers, rows) { doc.font('Helvetica-Bold').text(headers.join(' | ')); doc.font('Helvetica').text('-'.repeat(Math.min(110, headers.join(' | ').length))); for (const r of rows) doc.text(r.map(s).join(' | ')); doc.moveDown(.4); }
function signature(doc,p) { doc.addPage({margin:54}); doc.fontSize(15).font('Helvetica-Bold').text('Signatures'); doc.fontSize(9).font('Helvetica').text('In-app sign-off records are workflow records; formal legally-binding e-signature integration is pending.'); for (const x of (p.signatures||[])) { const so=(p.sign_offs||[]).find(y=>y.signatory_role===x.role_code&&y.status==='signed'); doc.moveDown(.7).fontSize(11).font('Helvetica-Bold').text(s(x.role)); doc.fontSize(10).font('Helvetica').text(so ? `Signed by ${s(so.signatory_name)}${so.signed_at ? ` on ${String(so.signed_at).slice(0,10)}` : ''}` : 'Signature: ______________________________    Printed name: ______________________________    Date: ______________'); } }
function base(p,title,body) { const d=new PDFDocument({margin:54,bufferPages:true}); const chunks=[]; d.on('data',x=>chunks.push(x)); const done=new Promise((resolve,reject)=>{d.on('end',()=>resolve(Buffer.concat(chunks)));d.on('error',reject)}); d.fontSize(18).font('Helvetica-Bold'); for(const x of lines(p,title)) d.text(x).moveDown(.2); d.moveDown(.7).fontSize(11).font('Helvetica'); body(d); signature(d,p); d.end(); return done; }
export function pdfForReport(p) { return base(p,'Functional Behavior Assessment Report',d=>{ const c=p.client||{}; d.font('Helvetica-Bold').text('Client information');d.font('Helvetica');addTable(d,['Field','Value'],[['Name',`${s(c.first_name)} ${s(c.last_name)}`],['Date of birth',c.date_of_birth],['Gender',c.gender],['Consent',c.consent_status_label]]); d.font('Helvetica-Bold').text('Target behaviors');d.font('Helvetica');addTable(d,['Behavior','Operational definition','Safety','Measurement'],(p.behaviors||[]).map(b=>[b.name,b.operational_definition,b.safety_classification_label,b.baseline_measurement_type_label])); d.font('Helvetica-Bold').text('Data summary');d.font('Helvetica');addTable(d,['Behavior','Observations','Statistics'],(p.data_summary?.per_behavior_stats||[]).map(x=>[x.target_behavior_name,x.stats?.count??(p.data_summary.per_behavior||[]).find(y=>y.target_behavior_id===x.target_behavior_id)?.count,x.stats?.mean!=null?`Mean ${x.stats.mean}`:''])); d.font('Helvetica-Bold').text('ABC analysis');d.font('Helvetica');(p.abc||[]).forEach(x=>d.text(`${x.target_behavior_name}: Top antecedents ${(x.top_antecedents||[]).map(y=>`${y.label} (${y.count})`).join(', ')||'none recorded'}; Top consequences ${(x.top_consequences||[]).map(y=>`${y.label} (${y.count})`).join(', ')||'none recorded'}`)); d.font('Helvetica-Bold').text('Function hypotheses');d.font('Helvetica');addTable(d,['Behavior','Function','Confidence','Rationale'],(p.hypotheses||[]).map(h=>[h.target_behavior_name,h.function_label,pct(h.confidence),`${s(h.rationale)} ${s(h.interpretation)}`])); d.font('Helvetica-Bold').text('Data quality');d.font('Helvetica').text(`ABC completeness: ${pct(p.data_quality?.data_completeness)}`);(p.data_quality?.notes||[]).forEach(x=>d.text(`• ${s(x?.text||x)}`)); }); }
export function pdfForBip(p) { return base(p,'Behavior Intervention Plan',d=>{(p.behaviors||[]).forEach(b=>{d.font('Helvetica-Bold').text(b.name);d.font('Helvetica').text(`Definition: ${s(b.operational_definition)}\nSafety: ${s(b.safety_classification_label)}\nHypothesized function: ${b.hypothesized_function?`${b.hypothesized_function.function_label} (${pct(b.hypothesized_function.confidence)})`:'Not yet established'}`); for(const [h,xs] of [['Antecedent strategies',b.antecedent_strategies],['Replacement skills',[b.replacement_skills?.description,`Mastery criteria: ____________________    Review interval: ____________________`,b.replacement_skills?.prompting_note]],['Consequence strategies',b.consequence_strategies],['Data collection plan',[b.data_collection_plan?.data_sheet_reference]]]) {d.font('Helvetica-Bold').text(h);d.font('Helvetica');(xs||[]).forEach(x=>d.text(`• ${s(x?.text||x)}`));}}); }); }
export function pdfForCrisis(p) { return base(p,'Crisis Procedure / Safety Plan',d=>{d.font('Helvetica-Bold').text('Trigger behaviors');d.font('Helvetica');if(p.has_triggers)(p.trigger_behaviors||[]).forEach(b=>d.text(`${b.name}: Definition: ${s(b.operational_definition)} | Classification: ${s(b.safety_classification_label)}\n${s(b.guidance)}`));else d.text(s(p.empty_state_note));d.font('Helvetica-Bold').text('Response steps');d.font('Helvetica');(p.response_steps||[]).forEach((x,i)=>d.text(`${i+1}. ${s(x?.text||x)}`));d.font('Helvetica-Bold').text('Roles');d.font('Helvetica');addTable(d,['Role','Name','Duty'],(p.roles||[]).map(x=>[x.role,x.name,x.duty]));d.font('Helvetica-Bold').text('Debrief');d.font('Helvetica');(p.debrief?.steps||[]).forEach(x=>d.text(`• ${s(x?.text||x)}`));d.text('Debrief date: __________________  Participants: __________________  Review notes: __________________');d.font('Helvetica-Bold').text('Emergency contacts');d.font('Helvetica');addTable(d,['Contact','Details'],[['Primary',p.emergency_contacts?.contact_1],['Secondary',p.emergency_contacts?.contact_2],['Local emergency number',p.emergency_contacts?.local_emergency_number]]); }); }
export function pdfForDataSheet(p) { return base(p,'Blank Observation Data Sheet',d=>{d.text(s(p.observation_instructions));if(!(p.sheets||[]).length)d.text('No target behaviors have been defined; no data sheets are available.');(p.sheets||[]).forEach(sh=>{d.font('Helvetica-Bold').text(sh.behavior_name);d.font('Helvetica').text(`Operational definition: ${s(sh.operational_definition)} | Measurement: ${s(sh.measurement_type_label)}`);addTable(d,['Date / Time','Setting','Antecedent','Consequence',sh.value_column_label],Array.from({length:20},()=>['','','','','']));}); }); }
export function pdfForProgressReport(p) { return base(p,`Progress Report — ${s(p.period_label)}`,d=>{d.font('Helvetica-Bold').text('Executive summary');d.font('Helvetica').text(s(p.executive_summary));d.font('Helvetica-Bold').text('Key behavior metrics');d.font('Helvetica');addTable(d,['Behavior','Points','Frequency mean/day','Trend'],(p.metrics?.per_behavior||[]).map((m,i)=>{const t=(p.trends?.per_behavior||[])[i]||{};return [m.behavior_name,m.point_count,m.frequency_mean_per_observation_day==null?'—':Number(m.frequency_mean_per_observation_day).toFixed(2),t.direction==='worsened'?'▲ worsened':t.direction==='improved'?'▼ improved':t.direction==='stable'?'→ stable':'— baseline']}));d.font('Helvetica-Bold').text('Plan-adjustment recommendations');d.font('Helvetica');const r=(p.recommendations||[]).map(x=>`${String(x.priority).toUpperCase()} — ${x.text} (${x.timeframe})`);(r.length?r:['No recommendations recorded.']).forEach((x,i)=>d.text(`${i+1}. ${x}`));d.font('Helvetica-Bold').text('Implementation plan');d.font('Helvetica').text('Action | Owner | Due\n________________ | ________________ | ________________');d.text(s(p.not_yet_available)); }); }
