// Period-based progress reporting. Frequency direction is problem-behavior oriented:
// a decrease >=20% is improved, increase >=20% worsened, otherwise stable.
import db from './db.js';
const MONTH_NAMES=['January','February','March','April','May','June','July','August','September','October','November','December'];
export function parsePeriod(type, period){
 if(type==='month' && /^\d{4}-(0[1-9]|1[0-2])$/.test(period)){ const [y,m]=period.split('-').map(Number); const start=`${period}-01`; const end=new Date(Date.UTC(y,m,1)).toISOString().slice(0,10); return {start,end,label:`${MONTH_NAMES[m-1]} ${y}`}; }
 if(type==='quarter' && /^(\d{4})-Q([1-4])$/.test(period)){ const [,ys,qs]=period.match(/^(\d{4})-Q([1-4])$/); const y=Number(ys), q=Number(qs), m=(q-1)*3+1; const start=`${y}-${String(m).padStart(2,'0')}-01`; const end=new Date(Date.UTC(y,m+2,1)).toISOString().slice(0,10); return {start,end,label:`Q${q} ${y}`}; }
 return null;
}
function previous(type, period){ const p=parsePeriod(type,period); if(!p)return null; const d=new Date(`${p.start}T00:00:00Z`); d.setUTCMonth(d.getUTCMonth()-(type==='quarter'?3:1)); return type==='month'?`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`:`${d.getUTCFullYear()}-Q${Math.floor(d.getUTCMonth()/3)+1}`; }
async function aggregate(assessmentId, range, behaviors){
 const points=await db.prepare('SELECT * FROM data_points WHERE assessment_id=? AND recorded_at>=? AND recorded_at<? ORDER BY recorded_at').all(assessmentId,range.start,range.end);
 const out=behaviors.map(b=>{ const ps=points.filter(p=>p.target_behavior_id===b.id), freq=ps.filter(p=>p.measurement_type==='frequency'), days=new Set(freq.map(p=>String(p.recorded_at).slice(0,10))); const vals=ps.filter(p=>p.measurement_type!=='frequency').map(p=>p.value); const settings={}; ps.forEach(p=>{if(p.setting)settings[p.setting]=(settings[p.setting]||0)+1}); const complete=ps.length?ps.filter(p=>p.setting&&p.antecedent&&p.consequence).length/ps.length:0; const mean=freq.length?(freq.reduce((s,p)=>s+p.value,0)/Math.max(1,days.size)):null; return {behavior_id:b.id,behavior_name:b.name,point_count:ps.length,frequency_total:freq.reduce((s,p)=>s+p.value,0),frequency_mean_per_observation_day:mean,duration_latency_mean:vals.length?vals.reduce((s,v)=>s+v,0)/vals.length:null,duration_latency_min:vals.length?Math.min(...vals):null,duration_latency_max:vals.length?Math.max(...vals):null,safety_incidents:b.is_safety_concern?ps.length:0,data_completeness_pct:Math.round(complete*100),top_settings:Object.entries(settings).sort((a,z)=>z[1]-a[1]).slice(0,3).map(([setting,count])=>({setting,count}))}; });
 return {points,out,total_points:points.length,complete_points:points.filter(p=>p.setting&&p.antecedent&&p.consequence).length};
}
export async function buildProgressReport(assessmentId,type,period){ const parsed=parsePeriod(type,period); if(!parsed)return null; const a=await db.prepare('SELECT * FROM assessments WHERE id=? AND deleted_at IS NULL').get(assessmentId); if(!a)return null; const behaviors=await db.prepare('SELECT * FROM target_behaviors WHERE assessment_id=? ORDER BY id').all(assessmentId); const cur=await aggregate(assessmentId,parsed,behaviors); const prevPeriod=previous(type,period), prevParsed=parsePeriod(type,prevPeriod), prev=await aggregate(assessmentId,prevParsed,behaviors); const trends=cur.out.map((m,i)=>{const pm=prev.out[i], current=m.frequency_mean_per_observation_day, old=pm.frequency_mean_per_observation_day; const fallback=current==null||old==null; const change=fallback?null:(old===0?(current===0?0:100):((current-old)/old)*100); return {behavior_id:m.behavior_id,behavior_name:m.behavior_name,prev_period_label:prevParsed.label,current_mean:current,prev_mean:old,change_pct:change,direction:!prev.points.length||fallback?'baseline':change<=-20?'improved':change>=20?'worsened':'stable'}; });
 const rec=[]; cur.out.forEach((m,i)=>{const t=trends[i]; if(m.point_count<3)rec.push({priority:'high',text:`Insufficient data — increase data collection for ${m.behavior_name}.`,timeframe:'Within 2 weeks'}); if(m.safety_incidents)rec.push({priority:'high',text:'Safety-flagged behavior still occurring — prioritize crisis plan review.',timeframe:'Within 2 weeks'}); if(t.direction==='worsened')rec.push({priority:'high',text:'Plan revision recommended — review antecedents/consequences and consider strengthening supports.',timeframe:'Within 2 weeks'}); else if(t.direction==='stable')rec.push({priority:'medium',text:'Continue current plan; monitor.',timeframe:'Next scheduled review'}); else if(t.direction==='improved')rec.push({priority:'low',text:'Positive progress — consider fading support and generalizing.',timeframe:'Next review'}); if(m.data_completeness_pct<70)rec.push({priority:'medium',text:'Improve ABC completeness for reliable analysis.',timeframe:'Within 2 weeks'}); }); rec.sort((x,y)=>({high:0,medium:1,low:2}[x.priority]-({high:0,medium:1,low:2}[y.priority]))); rec.splice(6);
 const improvements=trends.filter(t=>t.direction==='improved').length, concerns=trends.filter(t=>t.direction==='worsened').length; const executive_summary=cur.total_points?`${parsed.label} includes ${cur.total_points} recorded observation${cur.total_points===1?'':'s'} across ${behaviors.length} target behavior${behaviors.length===1?'':'s'}. ${improvements?`${improvements} behavior${improvements===1?' shows':'s show'} positive progress`:concerns?`${concerns} behavior${concerns===1?' requires':'s require'} plan review`:'Continue monitoring current patterns'}. ${rec[0]?rec[0].text:'Continue collecting data to support clinical decisions.'}`:`No observations were recorded during ${parsed.label}. Increase data collection before interpreting progress.`;
 const client=await db.prepare('SELECT * FROM clients WHERE id=?').get(a.client_id); return {assessment_id:Number(assessmentId),assessment:a,client,period_type:type,period,period_label:parsed.label,date_range:parsed,executive_summary,metrics:{per_behavior:cur.out,totals:{point_count:cur.total_points,complete_points:cur.complete_points,data_completeness_pct:cur.total_points?Math.round(cur.complete_points/cur.total_points*100):0}},trends:{per_behavior:trends},recommendations:rec,generated_at:new Date().toISOString(),is_preliminary:true,not_yet_available:'Skill-acquisition metrics, goal attainment, and inter-rater reliability are not yet in the data model; these are planned future phases.'}; }
export { previous };
